FROM amd64/python:3.7-slim-buster

WORKDIR /app

RUN echo 'asd'
RUN apt-get update

RUN pip3 install --upgrade pip
RUN pip install --upgrade setuptools

COPY requirements.txt ./
RUN apt-get install -y libgpiod2
RUN pip3 install -r requirements.txt

COPY . .

USER root:root

CMD [ "python3", "-u", "./main.py" ]